<?php 
include_once '/HeaderController.php';
include_once '/JScontroller.php';
echo $this->doctype() . "\n" 
?>
<html class="no-js" lang="pt-br">
<head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
	<meta name="viewport" content="width=1020" />

	<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
	<meta http-equiv="Pragma" content="no-cache" />

	<meta name="robots" content="index, follow" />
	<meta name="robot" content="All" />
	<meta name="language" content="pt-br" />
	<meta name="author" content="Mateus Martins | mateusweb@gmail.com" />
	<meta name="MSSmartTagsPreventParsing" content="true" />
	<meta name="rating" content="general" />
	<meta name="distribuition" content="global" />
	
	<meta name="title" content="Nadeb | Sistema de Gerenciamento" />
	<meta name="keywords" content="" />
	<meta name="description" content="" />

	<link rel="icon" type="image/x-icon" href="<?php echo __ROOT__ ?>public/admin/images/favicon.ico" />
	
	<?php echo HeaderController::load() ?>
	
	<?php echo JScontroller::load() ?>
	
	<title>Nadeb | Sistema de Gerenciamento</title>
</head>
<body>
	
	<header id="header">
		<div class="wrapper">
			<h1><a href="<?php echo __LINKS__ ?>admin/">Sistema de Gerenciamento</a></h1>
			<nav class="nav">
				<?php echo $this->menu($this->menuLinks) ?>
			</nav>
		</div>
	</header>
	
	<section id="section">
		<article class="article">
			<?php echo $this->Breadcrumbs( $this->breadCrumb ); ?>	
			<?php echo $this->layout()->content  . "\n" ?>
		</article>
		<aside class="sidebar">
			<?php echo $this->sideBar($this->sideBarlinks) ?>
		</aside>
	</section>

	<footer id="footer">
		<a href="https://code.google.com/p/nadeb5/">Nadeb5 - <strong>A very ease libcode</strong></a>
	</footer>

</body>
</html>







