<?php 
include_once '/HeaderController.php';
include_once '/JScontroller.php';
echo $this->doctype() . "\n" 
?>
<html class="no-js" lang="pt-br">
<head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
	<meta name="viewport" content="width=1020" />

	<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
	<meta http-equiv="Pragma" content="no-cache" />

	<meta name="robots" content="index, follow" />
	<meta name="robot" content="All" />
	<meta name="language" content="pt-br" />
	<meta name="author" content="Mateus Martins | mateusweb@gmail.com" />
	<meta name="MSSmartTagsPreventParsing" content="true" />
	<meta name="rating" content="general" />
	<meta name="distribuition" content="global" />
	
	<meta name="title" content="Nadeb Sample" />
	<meta name="keywords" content="" />
	<meta name="description" content="" />

	<link rel="icon" type="image/x-icon" href="<?php echo __ROOT__ ?>public/admin/images/favicon.ico" />

	<!--[if lt IE 9]><script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->

	<link href="<?php echo __ROOT__ ?>public/site/css/.reset.css" media="screen" rel="stylesheet" type="text/css" />
	<link href="<?php echo __ROOT__ ?>public/site/css/.style.css" media="screen" rel="stylesheet" type="text/css" />
	
	<script src="<?php echo __ROOT__ ?>public/site/js/jquery-min.js" type="text/javascript"></script>
	<script src="<?php echo __ROOT__ ?>public/site/js/site.js" type="text/javascript"></script>
	
	<?php echo HeaderController::load() ?>
	
	<title>Nadeb Sample</title>
</head>
<body>
	
	<header id="header">
		<div class="wrapper">
			<h1><a href="<?php echo __LINKS__ ?>/">Página Inicial</a></h1>
			<nav class="nav"></nav>
		</div>
	</header>
	
	<section id="section">
		<?php echo $this->layout()->content  . "\n" ?>
		<aside class="sidebar"></aside>
	</section>

	<footer id="footer"></footer>
	
</body>
</html>